### ISSUE TITLE
Not a Lab

### ISSUE THREAD

**Issue by bmanek** [learn-co-curriculum/react-updating-state#13] opened 2019-06-04 21:03 UTC
Echoing jdbean's remarks, this ReadMe/Code-Along has not been fully transitioned - there is no test folder, so it can't be completed without modification.

**Comment by maxwellbenton** [comment] 2019-09-26 00:00
Hi @bmanek,

Thank you for opening this issue. Unfortunately, I am unable to replicate the issue you experienced. This code-along should not require tests. Code-alongs, however, _do_ require some change to the code or files and the use of `learn submit` to register completion. Currently, this lesson is behaving as intended on Learn, so I am going to close this issue. 

We apologize for any frustration this may have caused.

**Closed by maxwellbenton** 2019-09-26 00:00 UTC
